export const LEGACY_HASH_TARGETS = {
  "tiktok-symphony": "/work/symphony",
  "tiktok-symphony-creative-studio": "/work/symphony",
  "meta-privacy": "/work/consent",
  "meta-privacy-systems-accounts-playback-and-ds90": "/work/consent",
  "uber-verticals-framework": "/work/reserve",
  "uber-hourly": "/work/reserve",
  "uber-hourly-reserve-and-group-rides": "/work/reserve",
  "uber-reserve": "/work/reserve",
  "uber-multi-driver-dispatch": "/work/reserve",
  "uber-driver-tablet-experience": "/work/reserve",
  "uber-driver-tablet-and-multi-driver-dispatch": "/work/reserve",
  "uber-fleet-match": "/work/reserve",
  "uber-intercity": "/work/reserve",
  "boeing-deliveries": "/work/deliveries",
  "boeing-doc-it-and-insite": "/work/deliveries",
  "boeing-insite": "/work/deliveries",
  "boeing-search": "/work/deliveries",
  "boeing-enterprise-search-and-searchdex": "/work/deliveries",
  "uber-share": "/catalog",
  "uber-group-rides-uber-pool": "/catalog",
  "uber-identity-hub": "/catalog",
  "uber-hq-candidate-experience": "/catalog",
  "uber-candidate-app": "/catalog",
  "expedia-lists": "/catalog",
  "expedia-scratchpad-and-lists": "/catalog",
  "expedia-travelgraph": "/catalog",
  "expedia-amp": "/catalog",
  "expedia-bots": "/catalog",
  "expedia-voice-bots": "/catalog",
  "boeing-plato": "/catalog",
  "boeing-plato-planning-tool": "/catalog",
} as const;

export const LEGACY_HASH_SCRIPT = `(function(){if(location.pathname!=='/'||!location.hash)return;try{var h=decodeURIComponent(location.hash.slice(1)).toLowerCase();var m=${JSON.stringify(LEGACY_HASH_TARGETS)};var t=Object.prototype.hasOwnProperty.call(m,h)?m[h]:null;if(t){location.replace(t+location.search);}else{history.replaceState(null,'',location.pathname+location.search);}}catch(e){history.replaceState(null,'',location.pathname+location.search);}})();`;
